// Generated by export_verified_body_layout.py; body only.
(()=>{
const send=()=>{};
const PROBE_ALL_CN=true;
(()=>{
const bodyContext=(()=>{
'use strict';

// Mirrors the verified TDA02 single-record branch at 31ffa6..3200d0.
// Pure calculation only: callers must establish the current mode, group and
// source record count. It intentionally does not guess multi-speaker geometry.
function resolveBodyGeometry({mode, sourceCount, groups, area=null, nameWidths=null}) {
  if (!Number.isInteger(sourceCount)||sourceCount<1) return {status:'unresolved',reason:'Absent or invalid source records'};
  if (mode !== 0 && mode !== 1) return {status:'unresolved',reason:'Unknown display mode'};
  const group=groups[mode];
  if (!group) return {status:'unresolved',reason:'Selected display group absent'};
  const v=group.values || group, f=Math.fround;
  const get=key=>{
    const value=v[key];
    if (!Number.isFinite(value)) throw Error('Invalid geometry '+key);
    return f(value);
  };
  if(sourceCount>1){
    // 320300..32036c measures all names before 3203f0..3204ab lays out
    // each body. Do not reuse a width from a previous update or record set.
    if(!Array.isArray(nameWidths)||nameWidths.length!==sourceCount)
      return {status:'unresolved',reason:'Current name measurements unavailable'};
    if(!nameWidths.every(w=>Number.isFinite(w)&&w>=0))throw Error('Invalid name width');
    const maxNameWidth=Math.max(0,...nameWidths.map(f));
    const left=f(f(get('0x1bc')+maxNameWidth)+8);
    const right=f(f(get('0x1bc')+get('0x1c4'))+get('0x1d4'));
    const width=f(right-left);
    if(!(width>0))return {status:'unresolved',reason:'Name column exhausts body width'};
    // The second float argument is a cumulative vertical cursor, initially
    // zero, then advanced after each body. It is NOT a fixed line height.
    return {status:'resolved',groupIndex:mode,left,right,width,maxNameWidth,verticalUnmodelled:true};
  }
  const startY=get('0x1ac');
  let left=get('0x1c8'), right=f(left+get('0x1d0'));
  let x=get('0x1a0'), top=get('0x1a4'), bottom=top;
  if (area !== null) {
    if (!Array.isArray(area)||area.length!==4||!area.every(Number.isFinite))
      throw Error('Invalid explicit area');
    const [ax,ay,aw,ah]=area.map(f);
    left=0;
    right=f(get('0x198')*aw);
    x=f(f(get('0x198')*ax)+get('0x190'));
    top=f(f(get('0x19c')*ay)+get('0x194'));
    bottom=f(f(f(get('0x19c')*f(ay+ah))+get('0x194'))-startY);
  }
  const width=f(right-left);
  if (!(width>0)) return {status:'unresolved',reason:'Nonpositive width'};
  return {status:'resolved',groupIndex:mode,left,right,width,startY,x,top,bottom};
}
if(typeof module!=='undefined')module.exports={resolveBodyGeometry};

const base=Process.mainModule.base, active=new Map(), seen=new Set();
function text(p){
 const n=p.add(16).readU64().toNumber(),cap=p.add(24).readU64().toNumber();
 if(n>10000||cap<n)throw Error('Invalid string');
 return(cap>15?p.readPointer():p).readUtf8String(n);
}
function emit(row){const k=JSON.stringify(row);if(!seen.has(k)){seen.add(k);send(row);}}
function geometry(owner){
 const begin=owner.add(0xd0).readPointer(),end=owner.add(0xd8).readPointer();
 const count=end.sub(begin).toInt32()/0x1e8;
 if(!Number.isInteger(count)||count<0||count>20)throw Error('Unexpected display group vector');
 const fields=[0x190,0x194,0x198,0x19c,0x1a0,0x1a4,0x1ac,0x1b0,0x1bc,0x1c4,0x1c8,0x1d0,0x1d4];
 return Array.from({length:count},(_,i)=>{
  const node=begin.add(i*0x1e8), values={};
  for(const o of fields)values['0x'+o.toString(16)]=node.add(o).readFloat();
  return {node:node.toString(),values};
 });
}
function currentGeometry(current){
 const application=base.add(0xa40080).readPointer().add(0x18).readPointer();
 const getter=application.readPointer().add(0x208).readPointer();
 if(!getter.equals(base.add(0x1bf8b0)))throw Error('Unverified display-mode getter');
 const mode=application.add(0x7f0).readS32();
 const first=current.model.add(0x1e0).readPointer(),last=current.model.add(0x1e8).readPointer();
 const sourceCount=last.sub(first).toInt32()/0xb0;
 if(!Number.isInteger(sourceCount)||sourceCount<0||sourceCount>100)throw Error('Invalid source count');
 const region=current.model.add(0x2a8).readPointer();
 const area=region.isNull()?null:[0,4,8,12].map(o=>region.add(o).readFloat());
 const groups=geometry(current.owner);
 const nameWidths=current.names.get(groups[mode]?.node)??null;
 return {mode,sourceCount,area,groups,nameWidths,predicted:resolveBodyGeometry({mode,sourceCount,area,groups,nameWidths})};
}
Interceptor.attach(base.add(0x31fc30),{
 onEnter(a){this.tid=Process.getCurrentThreadId();this.previous=active.get(this.tid);
  active.set(this.tid,{owner:a[0],model:a[1],names:new Map()});},
 onLeave(){if(this.previous)active.set(this.tid,this.previous);else active.delete(this.tid);}
});
// Immediately after the game's own name-size query. Read its returned width
// without invoking native methods; preserve the order within this update.
Interceptor.attach(base.add(0x32034f),{onEnter(){try{
 const current=active.get(Process.getCurrentThreadId());if(!current)return;
 const key=this.context.rbx.toString(),width=this.context.rbp.sub(0x50).readFloat();
 if(!Number.isFinite(width)||width<0)throw Error('Invalid measured name width');
 const values=current.names.get(key)||[];values.push(width);current.names.set(key,values);
}catch(e){send({kind:'context-error',stage:'names',error:String(e)});}}});

return {current:()=>active.has(Process.getCurrentThreadId())};})();
function parts(s){
 // Controls belong to the native parser. Never split an unparsed command.
 if(/[\\\r\n\t]/.test(s))return [s];
 // Keep combining marks, variation selectors and ZWJ sequences attached.
 const a=[];
 for(const c of Array.from(s)){
  if(a.length&&(/[\p{M}\u200d]/u.test(c)||a[a.length-1].endsWith('\u200d')))a[a.length-1]+=c;
  else a.push(c);
 }
 const out=[];let pending='';
 const latin=c=>/^[\p{Script=Latin}\p{N}][\p{Script=Latin}\p{N}\p{M}]*$/u.test(c);
 const open='（〔［｛〈《「『【〖〘〚“‘([{',close='、。，．！？：；％‰℃°）〕］｝〉》」』】〗〙〛”’)]},.!?:;%';
 for(let i=0;i<a.length;i++){
  let c=a[i];
  if(open.includes(c)){pending+=c;continue;}
  if(latin(c)){
   while(i+1<a.length){
    if(latin(a[i+1]))c+=a[++i];
    else if(i+2<a.length&&"-./_:'’".includes(a[i+1])&&latin(a[i+2])){c+=a[++i];c+=a[++i];}
    else break;
   }
  }else if('—―…⋯～〜~'.includes(c)){
   while(i+1<a.length&&a[i+1]===c[0])c+=a[++i];
  }
  // Do not orphan expressive punctuation on a new line; keep its run whole.
  if(!pending&&out.length&&(close.includes(c)||/^[—―…⋯～〜~]+$/.test(c)||/^\s+$/.test(c)))out[out.length-1]+=c;
  else{out.push(pending+c);pending='';}
 }
 if(pending){if(out.length)out[out.length-1]+=pending;else out.push(pending);}
 if(out.join('')!==s)throw Error('text changed');return out;
}
// Pure planning stage: no pointer access or native mutation.
// `parts` supplies the tested text-boundary splitter.
function planChineseRows(rows) {
 if(!bodyContext.current())return rows.map(source=>({source,text:source.text,copy:true}));
 const result=[];
 const ordinary=r=>r.plain && r.text.length>0 && !/[\\\r\n\t]/.test(r.text);
 for(let i=0;i<rows.length;){
  const first=rows[i];
  if(!ordinary(first)){result.push({source:first,text:first.text,copy:true});i++;continue;}
  let j=i+1;
  while(j<rows.length && ordinary(rows[j]) && rows[j].meta===first.meta)j++;
  const group=rows.slice(i,j),text=group.map(r=>r.text).join('');
  // English-only runs retain the engine's original segmentation.
  if(!/[\u3400-\u9fff]/.test(text)){
   for(const row of group)result.push({source:row,text:row.text,copy:true});
  }else{
   const split=parts(text);
   if(split.join('')!==text)throw Error('Segmentation changed text');
   for(const token of split)result.push({source:first,text:token,copy:false});
  }
  i=j;
 }
 if(result.map(r=>r.text).join('')!==rows.map(r=>r.text).join(''))throw Error('Plan changed text');
 return result;
}
// Research only. TDA02 two-sentence probe; no installed hook/resource changes.
// `parts` is loaded by the Python runner from cn_wrap_prototype.js.
if (Process.mainModule.name.toLowerCase() !== 'tda00-win64vc14-release.exe')
 throw Error('Only the verified TDA02 executable is supported');
const base=Process.mainModule.base;
const pushCopy=new NativeFunction(base.add(0x31e0f0),'void',['pointer','pointer']);
const assignString=new NativeFunction(base.add(0x4e5a0),'pointer',['pointer','pointer','uint64']);
const destroyVector=new NativeFunction(base.add(0x311f10),'void',['pointer']);
function readText(p){
 const n=p.add(16).readU64().toNumber(),cap=p.add(24).readU64().toNumber();
 if(n>10000||cap<n)throw Error('Invalid string');
 return (cap>15?p.readPointer():p).readUtf8String(n);
}
function emptyVector(){const p=Memory.alloc(24);p.writeByteArray(new Uint8Array(24));return p;}
Interceptor.attach(base.add(0x3206f0),{
 // a[1] is a parser/rule selector, not the selected UI language. A TDA00
 // live sample used mode=1 for Chinese (selected=9); do not gate on a[1]==9.
 // This selected-language guard still requires per-caller multilingual review.
 onEnter(a){this.output=a[0];this.cn=base.add(0xa58f5c).readS32()===9;},
 onLeave(){
  if(PROBE_ALL_CN&&!this.cn)return;
  let replacement=null,scratch=null;
  try{
   const v=this.output,begin=v.readPointer(),end=v.add(8).readPointer();
   const count=end.sub(begin).toInt32()/128;
   if(!Number.isInteger(count)||count<1||count>200)return;
   const rows=[];
   for(let i=0;i<count;i++){
    const p=begin.add(i*128);
    const prefix=readText(p),annotation=readText(p.add(32));
    const controlBytes=p.add(112).readPointer().sub(p.add(104).readPointer()).toInt32();
    rows.push({p,text:readText(p.add(64)),prefix,annotation,controlBytes,plain:!prefix&&!annotation&&controlBytes===0,meta:p.add(96).readU64().toString()});
   }
   const text=rows.map(r=>r.text).join('');
   if(!PROBE_ALL_CN&&!text.includes('备受西雅图瞩目的龙浪中尉')&&!text.includes('以上是今天的成绩'))return;
   const plan=planChineseRows(rows),runs=plan.map(r=>r.text);
   if(plan.every(r=>r.copy))return;
   replacement=emptyVector();scratch=emptyVector();
   let source=null,item=null;
   for(const part of plan){
    if(part.copy){pushCopy(replacement,part.source.p);continue;}
    if(source!==part.source){
     destroyVector(scratch);scratch=emptyVector();
     pushCopy(scratch,part.source.p);item=scratch.readPointer();source=part.source;
    }
    const utf8=Memory.allocUtf8String(part.text);
    const length=unescape(encodeURIComponent(part.text)).length;
    assignString(item.add(64),utf8,length);
    pushCopy(replacement,item);
   }
   destroyVector(scratch);scratch=null;
   const old=emptyVector();old.writeByteArray(v.readByteArray(24));
   v.writeByteArray(replacement.readByteArray(24));
   replacement.writeByteArray(new Uint8Array(24));replacement=null;
   destroyVector(old);
   send({kind:'wrap-probe-applied',text,before:rows.map(({p,...r})=>r),after:runs});
  }catch(e){send({kind:'wrap-probe-error',error:String(e),stack:e.stack});}
  finally{if(scratch)destroyVector(scratch);if(replacement)destroyVector(replacement);}
 }
});
send({kind:'wrap-probe-ready',scope:PROBE_ALL_CN?'Chinese selected; preserve opaque records and metadata boundaries':'two Chinese sentences; preserve opaque records and metadata boundaries'});

})();
send({"kind": "family-layout-ready", "game": "tda00", "scope": "temporary body only; no history-break correction"});

})();
