// Generated by export_verified_body_layout.py; body only.
(()=>{
const send=()=>{};
// Research only: use native-owned deep copies; never edit EGPACK text.
const b=Process.mainModule.base;
const strCtor=new NativeFunction(b.add(0x52170),'pointer',['pointer','pointer']);
const strDtor=new NativeFunction(b.add(0x52890),'void',['pointer']);
const copyItem=new NativeFunction(b.add(0xdd050),'pointer',['pointer','pointer']);
const pushItem=new NativeFunction(b.add(0xdb4c0),'pointer',['pointer','pointer','pointer']);
const destroyItems=new NativeFunction(b.add(0xda0f0),'void',['pointer','pointer']);
const destroyVec=new NativeFunction(b.add(0xd9560),'void',['pointer']);
function textAt(p){let n=p.add(16).readU64().toNumber();if(n>10000)throw Error('string limit');return(p.add(24).readU64().toNumber()>15?p.readPointer():p).readUtf8String(n);}
function parts(s){
 // Controls belong to the native parser. Never split an unparsed command.
 if(/[\\\r\n\t]/.test(s))return [s];
 // Keep combining marks, variation selectors and ZWJ sequences attached.
 const a=[];
 for(const c of Array.from(s)){
  if(a.length&&(/[\p{M}\u200d]/u.test(c)||a[a.length-1].endsWith('\u200d')))a[a.length-1]+=c;
  else a.push(c);
 }
 const out=[];let pending='';
 const latin=c=>/^[\p{Script=Latin}\p{N}][\p{Script=Latin}\p{N}\p{M}]*$/u.test(c);
 const open='（〔［｛〈《「『【〖〘〚“‘([{',close='、。，．！？：；％‰℃°）〕］｝〉》」』】〗〙〛”’)]},.!?:;%';
 for(let i=0;i<a.length;i++){
  let c=a[i];
  if(open.includes(c)){pending+=c;continue;}
  if(latin(c)){
   while(i+1<a.length){
    if(latin(a[i+1]))c+=a[++i];
    else if(i+2<a.length&&"-./_:'’".includes(a[i+1])&&latin(a[i+2])){c+=a[++i];c+=a[++i];}
    else break;
   }
  }else if('—―…⋯～〜~'.includes(c)){
   while(i+1<a.length&&a[i+1]===c[0])c+=a[++i];
  }
  // Do not orphan expressive punctuation on a new line; keep its run whole.
  if(!pending&&out.length&&(close.includes(c)||/^[—―…⋯～〜~]+$/.test(c)||/^\s+$/.test(c)))out[out.length-1]+=c;
  else{out.push(pending+c);pending='';}
 }
 if(pending){if(out.length)out[out.length-1]+=pending;else out.push(pending);}
 if(out.join('')!==s)throw Error('text changed');return out;
}
// Pure planning stage: no pointer access or native mutation.
// `parts` supplies the tested text-boundary splitter.
function planChineseRows(rows) {
 const result=[];
 const ordinary=r=>r.plain && r.text.length>0 && !/[\\\r\n\t]/.test(r.text);
 for(let i=0;i<rows.length;){
  const first=rows[i];
  if(!ordinary(first)){result.push({source:first,text:first.text,copy:true});i++;continue;}
  let j=i+1;
  while(j<rows.length && ordinary(rows[j]) && rows[j].meta===first.meta)j++;
  const group=rows.slice(i,j),text=group.map(r=>r.text).join('');
  // English-only runs retain the engine's original segmentation.
  if(!/[\u3400-\u9fff]/.test(text)){
   for(const row of group)result.push({source:row,text:row.text,copy:true});
  }else{
   const split=parts(text);
   if(split.join('')!==text)throw Error('Segmentation changed text');
   for(const token of split)result.push({source:first,text:token,copy:false});
  }
  i=j;
 }
 if(result.map(r=>r.text).join('')!==rows.map(r=>r.text).join(''))throw Error('Plan changed text');
 return result;
}

Interceptor.attach(b.add(0xc6540),{
 onEnter(){this.out=this.context.rcx;this.cn=b.add(0xb03a18).readS32()===9&&this.returnAddress.equals(b.add(0xcae77));},
 onLeave(){
  if(!this.cn)return;
  const v=this.out,begin=v.readPointer(),end=v.add(8).readPointer(),n=end.sub(begin).toInt32()/128;
  if(!Number.isInteger(n)||n<1||n>200)return;
  let replacement=null;
  try{
   const rows=[];
   for(let i=0;i<n;i++){
    const p=begin.add(i*128),text=textAt(p.add(64));
    rows.push({p,text,meta:p.add(96).readU64().toString(),plain:!textAt(p)&&!textAt(p.add(32))&&p.add(104).readPointer().equals(p.add(112).readPointer())});
   }
   const planned=planChineseRows(rows);if(planned.every(r=>r.copy))return;
   replacement=Memory.alloc(24);replacement.writeByteArray(new Uint8Array(24));
   for(const r of planned){
    if(r.copy){pushItem(replacement,replacement.add(8).readPointer(),r.source.p);continue;}
    const item=Memory.alloc(128);copyItem(item,r.source.p);
    try{strDtor(item.add(64));strCtor(item.add(64),Memory.allocUtf8String(r.text));pushItem(replacement,replacement.add(8).readPointer(),item);}
    finally{destroyItems(item,item.add(128));}
   }
   const old=Memory.alloc(24);old.writeByteArray(v.readByteArray(24));
   v.writeByteArray(replacement.readByteArray(24));replacement.writeByteArray(new Uint8Array(24));replacement=null;destroyVec(old);
  }catch(e){send({kind:'body-layout-error',error:String(e)});}
  finally{if(replacement)destroyVec(replacement);}
 }
});

})();
